# General settings
name: 'graph-tf-model'      # Warning: 'debug' and 'test' are reserved name that have a special behavior

wandb: 'online'             # online | offline | disabled
gpus: 1                     # Multi-gpu is not implemented on this branch


resume: null            # If resume, path to ckpt file from outputs directory in main directory
test_only: '/home/kkm0476/CS471/DiGress/checkpoints/checkpoint_qm9_noH.ckpt' #qm9_noH
target: 'CCc1cncc(C)c1'
scaffold: 'O=C'
threshold: 0.0 # 0.00 / 0.15 / 0.30 / 1.00

check_val_every_n_epochs: 5
sample_every_val: 4
val_check_interval: null
samples_to_generate: 512       # We advise to set it to 2 x batch_size maximum
samples_to_save: 60
chains_to_save: 1
log_every_steps: 50
number_chain_steps: 50        # Number of frames in each gif

final_model_samples_to_generate: 512 # does not work
final_model_samples_to_save: 30
final_model_chains_to_save: 20

evaluate_all_checkpoints: False