# General settings
name: 'graph-tf-model'      # Warning: 'debug' and 'test' are reserved name that have a special behavior

wandb: 'disabled'             # online | offline | disabled
gpus: 1                     # Multi-gpu is not implemented on this branch



test_only: '/content/molecule-editing/checkpoints/checkpoint_qm9_noH.ckpt' # Use absoulte path
target: 'CCc1cncc(C)c1' # Target molecule SMILES
scaffold: 'O=C' # Scaffold(functional group) SMILES
threshold: 0.0 # 0.0: fully masking ~ 1.0: initialization only, we use 0.00 / 0.15 / 0.30 / 1.00


# does not modify below
check_val_every_n_epochs: 5
sample_every_val: 4
val_check_interval: null
samples_to_generate: 512       # We advise to set it to 2 x batch_size maximum
samples_to_save: 60
chains_to_save: 1
log_every_steps: 50
number_chain_steps: 50        # Number of frames in each gif

final_model_samples_to_generate: 512
final_model_samples_to_save: 30
final_model_chains_to_save: 20

evaluate_all_checkpoints: False